### PR TITLE
Add sending of custom data with `expressHandler`

### PR DESCRIPTION
**Pull request by ktsashes**
Allows the sending of custom data along with requests handled by the `raygunClient.expressHandler`. Users can set the value `raygunClient.expressCustomData` to a function, and that function will be passed the current error, as well as the current request being processed. The user can then return an object that will be passed along as the custom data for the function.

Includes additional section in the README as well as a test for it. Addresses request in issue #29

### CODE REVIEW

**Comment by fundead** [comment]
Cheers for your work on this one, at a glance it looks good and we'll look at getting it into the next release. We currently have our heads down with the next major Raygun feature but we should be able to get this PR merged within the next couple of weeks.

Regards,

Callum Gavin
Raygun Limited

**Comment by Paxa** [comment]
:+1:

**Comment by ktsashes** [comment]
Resolved conflict and brought the code back up to date. No major changes needed to be done, mostly just style changes to conform with new code style

**Comment by fundead** [comment]
Firstly, apologies for the delay in response, and thanks for your initial work and for bringing it back up to date. This has now been merged and will be released onto NPM shortly as v0.9.0.

**Pull request closed without merging**
