### PR TITLE
chore: #158 document why no-var-requires ignore is necessary

### PR DESCRIPTION
**Pull request by miquelbeltran**
### Description :memo:
- **Purpose**: Document why the `eslint` rule `no-var-requires` for the correct function of the project.
- **Approach**: Add comment on rule.

After removing the rule ignore, I started converting some imports.

For example, before it would be:

```js
const humanString = require("object-to-human-string");
```

After, it would be:

```js
import humanString from "object-to-human-string";
```

But this leads to errors:

```
lib/raygun.messageBuilder.ts:29:25 - error TS7016: Could not find a declaration file for module 'object-to-human-string'. '/home/miquel/dev/projects/raygun/raygun4node/node_modules/object-to-human-string/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/object-to-human-string` if it exists or add a new declaration (.d.ts) file containing `declare module 'object-to-human-string';`

29 import humanString from "object-to-human-string";
                           ~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in lib/raygun.messageBuilder.ts:29
```

I understand that this is because we cannot import JS modules this way, so decided to keep this rule as it is for now.
I have added a comment explaining why the rule ignore is necessary, and we can move to the next one.

**Type of change**

- [x] Tech-debt

**Updates**

- Updated `eslint.config.mjs` with commentary.

### Test plan :test_tube:

- No actual changes happening

### Author to check :eyeglasses:
- [x] Project and all contained modules builds successfully
- [x] Self-/dev-tested 
- [x] Unit/UI/Automation/Integration tests provided where applicable
- [x] Code is written to standards
- [x] Appropriate documentation written (code comments, internal docs)

### Reviewer to check :heavy_check_mark:
- [ ] Project and all contained modules builds successfully
- [ ] Change has been dev-/reviewer-tested, where possible
- [x] Unit/UI/Automation/Integration tests provided where applicable
- [x] Code is written to standards
- [x] Appropriate documentation written (code comments, internal docs)

### CODE REVIEW

**Comment by sumitramanga** [comment]
Just to confirm - We just stick to doing  `const humanString = require("object-to-human-string");` ?

**Review by sumitramanga — APPROVED** [review]
LGTM! I understand now that we use `require` 💫

**Comment by miquelbeltran** [comment]
Correct! we leave it as it is

**Comment by miquelbeltran** [comment]
waiting for merge as it depends on the other PRs

**Pull request merged**
