### PR TITLE
refactor: #158 remove no-useless-catch eslint rule

### LINKED ISSUE #158: eslint: remove ignored rules and fix issues
**Please describe your new feature request**

In the PR https://github.com/MindscapeHQ/raygun4node/pull/156 we setup `eslint` to be the linter platform for the project.

However, the configuration file contains several rules set to "off" in order to pass the lint checks without changing the project.

We should eventually enable them and cleanup the code as well.

**Describe the solution you'd like**

Remove the rules' definition from `eslint.config.mjs`:
- [x] `@typescript-eslint/no-explicit-any`
- [x] `@typescript-eslint/no-this-alias`
- [x] `@typescript-eslint/no-unused-vars`
- [x] `@typescript-eslint/no-var-requires`
- [x] `no-undef`
- [ ] `no-unreachable`
- [ ] `no-useless-catch`

In case there are rules that should be there, document why in the `eslint.config.mjs` file.

**Describe alternatives you've considered**

We should not leave those rules there if we plan to continue development with the plugin, as they prevent us from detecting possible issues earlier on.

**Additional context**

There are around ~120 warnings when removing the rules.

### PR DESCRIPTION
**Pull request by miquelbeltran**
### Description :memo:
- **Purpose**: Remove the `no-useless-catch` eslint rule ignore setting
- **Approach**: Remove rule and fix code
- **Depends on**: #177

- This change also concludes the `eslint` setup.
- Closes #158 

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)

**Updates**

- Removed rule from `eslint.config.mjs`
- Removed the useless `catch` statements.
  - A `catch` and `throw` is not necessary, since we can just throw the original error, and the `finally` block will be called anyway.

### Test plan :test_tube:

- Rerun the tests and eslint process.
- Only test files were affected.

### Author to check :eyeglasses:
- [x] Project and all contained modules builds successfully
- [x] Self-/dev-tested 
- [x] Unit/UI/Automation/Integration tests provided where applicable
- [x] Code is written to standards
- [x] Appropriate documentation written (code comments, internal docs)

### Reviewer to check :heavy_check_mark:
- [ ] Project and all contained modules builds successfully
- [ ] Change has been dev-/reviewer-tested, where possible
- [x] Unit/UI/Automation/Integration tests provided where applicable
- [x] Code is written to standards
- [x] Appropriate documentation written (code comments, internal docs)

### CODE REVIEW

**Comment by sumitramanga** [comment]
Personally, I think this is a good rule to keep to avoid redundant throwing and rethrowing errors. I see you've cleaned up a couple of files to avoid it which is good ! I'm keen to hear your thoughts on removing this rule

**Review by sumitramanga — APPROVED** [review]
LGTM 😄

**Comment by miquelbeltran** [comment]
>  I'm keen to hear your thoughts further on why we should remove this rule

Oh sorry, we are not really removing it, I didn't explain it correctly.

Rather, we are removing the ignore setting and going to the defaults :) I just prefer to have less custom configuration when possible and use the defaults when available.

**Comment by sumitramanga** [comment]
@miquelbeltran Ah whoops, I think I misunderstood! Go ahead and merge the PR :)

**Pull request merged**
