### PR TITLE
refactor!: #262 remove deprecated methods

### LINKED ISSUE #262: API: Remove deprecated `sendWithCallback`
**Please describe your new feature request**

Eventually remove deprecated method.

**Describe the solution you'd like**

As this will be a breaking change, either do with other breaking changes or plan a for a new major release.

**Describe alternatives you've considered**

Keep the method longer.

**Additional context**

None

### PR DESCRIPTION
**Pull request by miquelbeltran**
### Description :memo:
- **Purpose**: Removes deprecated methods
- **Approach**: Refactor
- Closes #262 

**Type of change**

**BREAKING CHANGE** - New release must bump the major version (i.e. from `1.2.0` to `2.0.0`)

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

**Updates**

- Removed `sendWithCallback` (users should migrate to use the async `send()` method)
- Removed `setUser` (users should use either `user(request)` callback or pass user info to the `send()` method)
- Updated tests.

### Test plan :test_tube:

- CI checks
- Examples should not be using these methods

### Author to check :eyeglasses:
- [x] Project and all contained modules builds successfully
- [x] Self-/dev-tested 
- [x] Unit/UI/Automation/Integration tests provided where applicable
- [x] Code is written to standards
- [x] Appropriate documentation written (code comments, internal docs)

### Reviewer to check :heavy_check_mark:
- [ ] Project and all contained modules builds successfully
- [ ] Change has been dev-/reviewer-tested, where possible
- [ ] Unit/UI/Automation/Integration tests provided where applicable
- [ ] Code is written to standards
- [ ] Appropriate documentation written (code comments, internal docs)

### CODE REVIEW

**Comment by miquelbeltran** [comment]
Note to self: need to update the README!

**Comment by sumitramanga** [comment]
@miquelbeltran Is there a console message that can be outputted when someone updates the package via terminal so that it's more obvious?

**Review by sumitramanga — COMMENTED** [review]
Just one review comment otherwise looks good!

**Comment by miquelbeltran** [comment]
> @miquelbeltran Is there a console message that can be outputted when someone updates the package via terminal so that it's more obvious?

I don't think we can control that. Upgrading major versions require developers to manually perform the change, and they should check the changelog before doing so. Nevertheless, if the application doesn't build after upgrading, that's why.

**Review by sumitramanga — APPROVED** [review]
Code LGTM!

**Pull request merged**
